version: '3'

services:
  Django_App:
    build: ./django_App
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_App:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./django_App/.env
    depends_on:
      - db

  Angular_App:
    build: ./angular_App
    container_name: angular_app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./angular_App:/usr/src/app
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - Django_App
      - Angular_App

  db:
    image: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
