# Generated by Django 5.1.1 on 2024-11-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_comment_id_alter_retweet_id_alter_tweet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='api.user'),
        ),
    ]
