# Generated by Django 5.1.1 on 2024-11-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_comment_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='disLikes',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_comments', to='api.user'),
        ),
    ]
